/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package owlet;

import org.junit.Test;
import static org.junit.Assert.*;
import java.lang.Exception;
import java.io.File;
import java.io.IOException;
import org.semanticweb.HermiT.ReasonerFactory;
import org.semanticweb.owlapi.apibinding.OWLManager;
import org.semanticweb.owlapi.model.IRI;
import org.semanticweb.owlapi.model.OWLClass;
import org.semanticweb.owlapi.model.OWLDataFactory;
import org.semanticweb.owlapi.model.OWLDataProperty;
import org.semanticweb.owlapi.model.OWLEntity;
import org.semanticweb.owlapi.model.OWLIndividual;
import org.semanticweb.owlapi.model.OWLNamedIndividual;
import org.semanticweb.owlapi.model.OWLOntology;
import org.semanticweb.owlapi.model.OWLOntologyCreationException;
import org.semanticweb.owlapi.model.OWLOntologyManager;
import org.semanticweb.owlapi.reasoner.OWLReasoner;
import org.semanticweb.owlapi.reasoner.OWLReasonerConfiguration;
import org.semanticweb.owlapi.reasoner.OWLReasonerFactory;
import org.semanticweb.owlapi.reasoner.SimpleConfiguration;
import org.semanticweb.owlapi.reasoner.ConsoleProgressMonitor;
import org.semanticweb.owlapi.reasoner.structural.StructuralReasoner;
import org.semanticweb.owlapi.model.OWLOntologyLoaderConfiguration;
import org.semanticweb.owlapi.rdf.turtle.parser.TurtleOntologyParser;
import org.semanticweb.owlapi.model.OWLDocumentFormat;
import org.semanticweb.owlapi.io.OWLOntologyDocumentSource;
import org.semanticweb.owlapi.io.FileDocumentSource;



public class AppTest {

    static App test_app = new App(); 

    @Test public void test_valid() throws Exception {

        OWLOntologyLoaderConfiguration loader_config = new OWLOntologyLoaderConfiguration();
        loader_config = loader_config.addIgnoredImport(IRI.create("http://sbols.org/v3#"));
        loader_config = loader_config.addIgnoredImport(IRI.create("http://bioprotocols.org/uml#"));
        loader_config = loader_config.addIgnoredImport(IRI.create("http://www.ontology-of-units-of-measure.org/resource/om-2/"));
        boolean status = test_app.validateOntology("resources/paml-good.ttl", loader_config);
        assertTrue(status);
    }

//    @Test public void test_invalid() throws Exception {
//
//        OWLOntologyLoaderConfiguration loader_config = new OWLOntologyLoaderConfiguration();
//        loader_config = loader_config.addIgnoredImport(IRI.create("http://sbols.org/v3#"));
//        loader_config = loader_config.addIgnoredImport(IRI.create("http://bioprotocols.org/uml#"));
//        loader_config = loader_config.addIgnoredImport(IRI.create("http://www.ontology-of-units-of-measure.org/resource/om-2/"));
//        boolean status = test_app.validateOntology("resources/paml-bad.ttl", loader_config);
//        assertFalse(status);
//    }

}
