class Strings:
    ALIQUOT = "aliquot"
    SAMPLE = "sample"
    METADATA = "metadata"
    DATA = "data"
    XARRAY = "xarray"
    JSON = "json"
    MASK = "mask"
    MEASUREMENT = "measurement"
    CONTENTS = "contents"
    SOURCE = "source"
