class Strings:
    ALIQUOT = "aliquot"
    SAMPLE = "sample"
    METADATA = "metadata"
    DATA = "data"
    XARRAY = "xarray"
    JSON = "json"
    MASK = "mask"
    MEASUREMENT = "measurement"
    CONTENTS = "contents"
    SOURCE = "source"
    TARGET = "target"
    CONTAINER = "container"
    LOCATION = "location"
    SAMPLE_LOCATION = "sample_location"
    CONCENTRATION = "concentration"
    REAGENT = "reagent"
    EDGE = "edge"
